# Generated by Django 3.1.5 on 2021-01-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Enter the book's natural language (e.g. English, French, Japanese, Korean etc.)", max_length=200)),
                ('book', models.ManyToManyField(help_text='Select a book for this language', to='catalog.Book')),
            ],
        ),
    ]
